
export const OPEN_LEFT = 'OPEN_LEFT';
export const OPEN_RIGHT = 'OPEN_RIGHT';

export const CHANGE_CITY_MAP = 'CHANGE_CITY_MAP';

export const SHOW_POPUP = 'SHOW_POPUP';


export const SHOW_TOP_MENU = 'SHOW_TOP_MENU';
export const SCROLL_TOP_MENU = 'SCROLL_TOP_MENU';
export const SHOW_WHITE_MENU = 'SHOW_WHITE_MENU';


export const API_LOAD_FUND_TYPES_LIST = 'API_LOAD_FUND_TYPES_LIST';
export const API_LOAD_PIF_LIST = 'API_LOAD_PIF_LIST';
export const API_LOAD_UK_LIST = 'API_LOAD_UK_LIST';
export const API_LOADING_UK_LIST = 'API_LOADING_UK_LIST';
export const API_LOAD_COMPANY = 'API_LOAD_COMPANY';
export const API_LOADING_COMPANY = 'API_LOADING_COMPANY';

export const SHOW_UK_SMALL_LIST = 'SHOW_UK_SMALL_LIST';
export const SHOW_UK_SMALL_LIST_MOBILE = 'SHOW_UK_SMALL_LIST_MOBILE';

export const SHOW_ACCORDION = 'SHOW_ACCORDION';

export const UK_TYPE_FILTER = 'UK_TYPE_FILTER';
export const UK_TYPE_FILTER_LIST = 'UK_TYPE_FILTER_LIST';

